### ISSUE TITLE
[HW3] lib.js

### ISSUE THREAD

**Issue by mmaghajani** [AUT-CEIT/ie#2]
تو فایل
lib.js
از بعضی خطوط ارور میگیره.
مثلا
let
رو نمیشناسه

**Comment by pi0** [comment]
Engine e js e browser ghadimi hast ehtemalan. az che browseri estefade mikoni ?

**Comment by pi0** [comment]
@mmaghajani Problem seems to be fixed by renaming `let` to `var` for older browsers compatibility, would you please confirm that ? [This Link](https://rawgit.com/AUT-CEIT/ie/master/2016/fall/HW-3/example.html)

**Comment by mmaghajani** [comment]
از 
chrome
استفاده میکنم 
ولی دارم از 
web storm
استفاده میکنم اون داره
let
رو ارور میگیره .
حالا اشکال داره به جای
let
از 
var 
استفاده کنم؟

**Comment by pi0** [comment]
@mmaghajani  you don't even need lib.js locally, it is served from git directly

**Comment by mmaghajani** [comment]
ممنون

**Comment by aaBadri** [comment]
i think it was because of IDE js version : it must be changed to ECMAScript 6
